apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prom-pvc
  labels:
      name: prometheus
  namespace: istio-system
spec:
  storageClassName: manual
  accessModes:
   - ReadWriteOnce
  resources:
   requests:
     storage: 4Gi